name: kdt-project-1

dependencies:
  - python=3.10
  - pip
  - pip:
      - streamlit
      - numpy
      - pandas
      - pytest
      - google-genai
      - argparse
      - pathlib
      - oracledb