name: kdt-project-1

dependencies:
  - python=3.10
  - pip
  - pip:
      - -e .
      - streamlit
      - numpy
      - pandas
      - pytest
      - google-genai
      - oracledb
      - setuptools<81
      - fg-data-profiling